spring:
  application:
    name: salted-fish-net-dish

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/sfnd

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sfnd
    username: root
    password: 123456
  jackson:
    time-zone: Asia/Shanghai
  # 单个文件最大 10MB（按需调整）
  servlet:
    multipart:
      max-file-size: 1024MB
  # 整个请求最大 10MB（需 >= 单文件限制）
      max-request-size: 10240MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
jwt:
  sign:
    secret: "hhyqbffbyqzkyyqcllhysfcqqywz" # 推荐32字节以上